# Docker-Compose document
# Ref : https://docs.docker.com/compose/compose-file/

version: "3"
services:
  app:
    build: ./dockerfile/node
    image: node:${TAG}
    container_name: node_service_${TAG}
    ports:
      - "8080:80"
    environment:
      - DOCKER_MODE=dev
    volumes:
      - ../:/repo/
    networks:
      - service_network

networks:
  service_network:
    driver: bridge
